version: '3.4'

services:
  game-service:
    image: ${DOCKER_REGISTRY-}game.service
    build:
      context: .
      dockerfile: src/GameService/GameService.Api/Dockerfile

  web-blazor:
    image: ${DOCKER_REGISTRY-}web-blazor
    build:
      context: .
      dockerfile: src/WebBlazor/WebBlazor.Server/Dockerfile
