apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scrummy-secretstore
  namespace: scrummy
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/scrummy-secrets.json
  - name: nestedSeparator
    value: "."
